# Introduction
**Description:** This notebook contain complete code of numpy discussed in Day-30 to Day-32\
**Author:** Shahid Umar\
**Email:** shahidumar@mail.com


# Numpy Indexing and Slicing

In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3,4,5,6,7])

In [3]:
a[0]

1

In [4]:
a[-1]

7

In [5]:
b = np.arange(0, 12, 2)
b

array([ 0,  2,  4,  6,  8, 10])

In [6]:
b[2]

4

## Slicing

In [7]:
c = b.reshape(2,3)
c

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [8]:
c[0]

array([0, 2, 4])

In [9]:
c = b.reshape(3,2)
c

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10]])

In [10]:
c[1]

array([4, 6])

In [11]:
c[c < 5]

array([0, 2, 4])

In [12]:
c[(c < 5) & (c > 7)]

array([], dtype=int32)

In [13]:
c[(c < 5) | (c > 7)]

array([ 0,  2,  4,  8, 10])

## Enlist boolean operators - conditional operator

---
## Making an array from a data or from another array

In [14]:
a = np.arange(0, 222, 5)
a

array([  0,   5,  10,  15,  20,  25,  30,  35,  40,  45,  50,  55,  60,
        65,  70,  75,  80,  85,  90,  95, 100, 105, 110, 115, 120, 125,
       130, 135, 140, 145, 150, 155, 160, 165, 170, 175, 180, 185, 190,
       195, 200, 205, 210, 215, 220])

In [15]:
len(a)

45

In [16]:
array1 = a[40:45]
array1

array([200, 205, 210, 215, 220])

In [17]:
a = np.array([1,2,3,4,5,6,7])
b = np.array([8,9,10,11,12,13,14])

- ### Array stacking
It's like a concatenation

In [18]:
# vertically stack
c = np.vstack((a,b))
c

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [19]:
# hotizontally stack
d = np.hstack((a,b))
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [20]:
d = d.reshape(2,7)
d

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

---
# Matrix or Matrices
---

In [21]:
# create 2x3 matrix
m = np.array([[1,2,3],[4,5,6]])
m

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# create a matrix big dimensions
b = np.arange(0,100,2)
b
# for reshaping we can add .reshape(0,100,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [23]:
b[1]

2

In [24]:
# Reshaping the matrix
b = b.reshape(5,10)
b

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [25]:
# slicing a matrix
b[1:3, 3:5]

array([[26, 28],
       [46, 48]])

### Let's understand the above code step by step

In [26]:
b[0:3, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [27]:
b[0:4, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48],
       [66, 68]])

In [28]:
b[:, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48],
       [66, 68],
       [86, 88]])

In [29]:
b[0:,]

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [30]:
# slicing a matrix of 3x2
b[0:3, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48]])

## Let's again from zero understanding

In [31]:
b[:,:] # All rows and all columns

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [80, 82, 84, 86, 88, 90, 92, 94, 96, 98]])

In [32]:
b[0:3,:] # display only first three rows

array([[ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58]])

In [33]:
b[0:3, 3:5]

array([[ 6,  8],
       [26, 28],
       [46, 48]])

In [34]:
b.max()

98

In [35]:
b.min()

0

In [36]:
b.sum()

2450

In [37]:
b.mean()

49.0

In [38]:
# maximum in rows
b.max(axis=0) # only for column

array([80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

In [39]:
# minimum in rows
b.min(axis=0)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [40]:
# maximum in columns
b.max(axis=1) # only for rows

array([18, 38, 58, 78, 98])

In [41]:
# minimum in columns
b.min(axis=1)

array([ 0, 20, 40, 60, 80])

In [42]:
m = np.arange(0,20,2).reshape(5,2)
m

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18]])

In [43]:
# adding two matrices
m + m

array([[ 0,  4],
       [ 8, 12],
       [16, 20],
       [24, 28],
       [32, 36]])

In [44]:
# adding values in existing matrix
m + np.array([20, 22])

array([[20, 24],
       [24, 28],
       [28, 32],
       [32, 36],
       [36, 40]])

In [45]:
# When adding new row with values
np.vstack((m, np.array([20, 22])))

array([[ 0,  2],
       [ 4,  6],
       [ 8, 10],
       [12, 14],
       [16, 18],
       [20, 22]])

In [46]:
# Reverse the full matrix
np.flip(b)

array([[98, 96, 94, 92, 90, 88, 86, 84, 82, 80],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [18, 16, 14, 12, 10,  8,  6,  4,  2,  0]])

In [47]:
# Reverse the matrix row wise
np.flip(b, axis=0)

array([[80, 82, 84, 86, 88, 90, 92, 94, 96, 98],
       [60, 62, 64, 66, 68, 70, 72, 74, 76, 78],
       [40, 42, 44, 46, 48, 50, 52, 54, 56, 58],
       [20, 22, 24, 26, 28, 30, 32, 34, 36, 38],
       [ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18]])

In [48]:
# Reverse the matrix column wise
np.flip(b, axis=1)

array([[18, 16, 14, 12, 10,  8,  6,  4,  2,  0],
       [38, 36, 34, 32, 30, 28, 26, 24, 22, 20],
       [58, 56, 54, 52, 50, 48, 46, 44, 42, 40],
       [78, 76, 74, 72, 70, 68, 66, 64, 62, 60],
       [98, 96, 94, 92, 90, 88, 86, 84, 82, 80]])